from collections.abc import Iterable
from typing import Optional

class SimplicialComplex:
    def __init__(self, facets: Iterable[Iterable[int]]) -> None: ...
    def compute_betti_number(self, dim: int) -> int: ...
    def compute_betti_numbers(self, dimensions: Optional[list[int]]) -> list[int]: ...
    def is_connected(self) -> bool: ...
    def add_simplex(self) -> None: ...
    def union(self) -> "SimplicialComplex": ...
    def k_faces(self, dim: int) -> list[list[int]]: ...
    
    @property
    def betti_numbers(self) -> list[int]: ...
    @property
    def dimension(self) -> int: ...
    @property
    def facets(self) -> list[list[int]]: ...
    @property
    def simplices(self) -> list[list[int]]: ...